### ISSUE TITLE
Bridge connected/disconnected every 10 seconds

### ISSUE THREAD

**Issue by jx11r** [qaisjp/go-discord-irc#127]
The bridge works fine, but I get this log every 10 seconds.

![image](https://user-images.githubusercontent.com/78786202/161441020-69a43033-8797-424e-b1e9-262fda1b64e9.png)

Config:
```yml
---
discord_token: my.discord.token
irc_server_name: oftc
irc_server: irc.oftc.net:6697
guild_id: 955163559086665728

# Default is as below
avatar_url: "https://robohash.org/${USERNAME}.png?set=set4"

# Updating this will automatically add or remove puppets from channels
channel_mappings:
  "#qtile chanKey": 955650645833162822

suffix: "[b]"
separator: "_"
irc_listener_name: "discord"
# puppet_username: "discord" # This will default to the discord username of the puppeted account
# webirc_pass: abcdef.ghijk.lmnop

show_joinquit: false # displays JOIN, PART, QUIT, KICK on discord
cooldown_duration: 259200 # optional, default 86400 (24 hours), time in seconds for a discord user to be offline before it's puppet disconnects from irc
max_nick_length: 30 # Maximum Length of a nick allowed

# You definitely should restart the bridge after changing the following:
insecure: false
no_tls: false
debug: false
simple: false

# irc_listener_prejoin_commands:
#   - PART #forced-to-join-test-channel
#   - PRIVMSG Nick :msg

# This is the default value, which makes sure that puppets
# are deafened (i.e. puppets do not need to hear anything!)
irc_puppet_prejoin_commands:
  - "MODE ${NICK} +D" # Note that for inspircd 3.x this should be +d!
# - "PRIVMSG NickServ IDENTIFY your-password-here" # this is how you can identify to NickServ!

# Uses matching syntax as in https://github.com/gobwas/glob
# ignored_irc_hostmasks:
#  - "bot1!*@*"
#  - "*!?bot@*"

# This limits to 2 connections (a listener, and one puppet, the rest relayed in simple mode)
# connection_limit: 2

# Prevent MEE6 from appearing on IRC
# ignored_discord_ids:
#  - 159985870458322944

# Only allow specific Discord users to appear on IRC
# allowed_discord_ids:
#  - 159985870458322944 # Only allow Mee6!
```
